### ISSUE TITLE
Shell error - wrong substitution

### ISSUE THREAD

**Issue by rafal-radziszewski** [bitwalker/exrm#369]
In exrm/priv/rel/files/boot:382 there is an argument substitution not supported in /bin/sh mode. On the fork I created I replaced the `!#/bin/sh` invocation to `!#/bin/bash` as temporary solution, but I guess using generally compatible `/bin/sh` is there for a reason. Right now any attempt to start server using master causes errors.

**Comment by bitwalker** [comment]
@rafal-radziszewski This one slipped past me :(. I've pushed a fix, please let me know if you run into any other issues.

**Comment by rafal-radziszewski** [comment]
@bitwalker Thanks for so instant reaction! I will test the package as soon as you bump relx (just been updated), so erlware_commons compile on 19.0.

**Comment by bitwalker** [comment]
Just did, and pushed a new release to hex (1.0.6) :)

**Comment by rafal-radziszewski** [comment]
@bitwalker I just tested it and my version got builded with OTP 19. Once again thanks for instantous update.

There is a problem however: though node runs, I don't seem to be able to attach to node using remote_console. I'm not sure if this is exrm issue, so I do not know if I should open another issue. I paste the output in case it would tell you more than me.

```
{error_logger,{{2016,6,29},{20,52,12}},"~s~n",["beam/beam_load.c(1486): Error loading module binary:\n  there are local calls to the stub for the BIF binary:split/3\n"]}
{error_logger,{{2016,6,29},{20,52,12}},supervisor_report,[{supervisor,{local,kernel_sup}},{errorContext,start_error},{reason,{'EXIT',{undef,[{binary,module_info,[module],[]},{code,'-load_code_server_prerequisites/0-lc$^0/1-0-',1,[{file,"code.erl"},{line,369}]},{code,load_code_server_prerequisites,0,[{file,"code.erl"},{line,369}]},{code,do_start,1,[{file,"code.erl"},{line,325}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,343}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,326}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,292}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]}]}}},{offender,[{pid,undefined},{id,code_server},{mfargs,{code,start_link,[]}},{restart_type,permanent},{shutdown,2000},{child_type,worker}]}]}
{error_logger,{{2016,6,29},{20,52,12}},crash_report,[[{initial_call,{application_master,init,['Argument__1','Argument__2','Argument__3','Argument__4']}},{pid,<0.33.0>},{registered_name,[]},{error_info,{exit,{{shutdown,{failed_to_start_child,code_server,{'EXIT',{undef,[{binary,module_info,[module],[]},{code,'-load_code_server_prerequisites/0-lc$^0/1-0-',1,[{file,"code.erl"},{line,369}]},{code,load_code_server_prerequisites,0,[{file,"code.erl"},{line,369}]},{code,do_start,1,[{file,"code.erl"},{line,325}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,343}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,326}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,292}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]}]}}}},{kernel,start,[normal,[]]}},[{application_master,init,4,[{file,"application_master.erl"},{line,134}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}},{ancestors,[<0.32.0>]},{messages,[{'EXIT',<0.34.0>,normal}]},{links,[<0.32.0>,<0.31.0>]},{dictionary,[]},{trap_exit,true},{status,running},{heap_size,987},{stack_size,27},{reductions,224}],[]]}
{error_logger,{{2016,6,29},{20,52,12}},std_info,[{application,kernel},{exited,{{shutdown,{failed_to_start_child,code_server,{'EXIT',{undef,[{binary,module_info,[module],[]},{code,'-load_code_server_prerequisites/0-lc$^0/1-0-',1,[{file,"code.erl"},{line,369}]},{code,load_code_server_prerequisites,0,[{file,"code.erl"},{line,369}]},{code,do_start,1,[{file,"code.erl"},{line,325}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,343}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,326}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,292}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]}]}}}},{kernel,start,[normal,[]]}}},{type,permanent}]}
{"Kernel pid terminated",application_controller,"{application_start_failure,kernel,{{shutdown,{failed_to_start_child,code_server,{'EXIT',{undef,[{binary,module_info,[module],[]},{code,'-load_code_server_prerequisites/0-lc$^0/1-0-',1,[{file,\"code.erl\"},{line,369}]},{code,load_code_server_prerequisites,0,[{file,\"code.erl\"},{line,369}]},{code,do_start,1,[{file,\"code.erl\"},{line,325}]},{supervisor,do_start_child,2,[{file,\"supervisor.erl\"},{line,343}]},{supervisor,start_children,3,[{file,\"supervisor.erl\"},{line,326}]},{supervisor,init_children,2,[{file,\"supervisor.erl\"},{line,292}]},{gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,328}]}]}}}},{kernel,start,[normal,[]]}}}"}
```

**Comment by bitwalker** [comment]
@rafal-radziszewski this is certainly a separate issue, I wonder if it's related to OTP 19 or something else entirely. A couple of things:

- Is the node you are trying to remote console to running? If so, we know the app starts, and the issue is likely in the code which handles connecting remotely.
- If not, did you build the release and deploy it using the same OS/Architecture?
- Do other commands work? i.e. `attach`, `ping`, etc.

I haven't yet made the leap to 19 because my current workload is all on 18 still, and I haven't had the time to really test it out yet, but I'll be finding some time soon to make the switch and iron out these kind of bugs. In the meantime, you'll have to be my eyes and ears ;)

**Comment by rafal-radziszewski** [comment]
1. Node is running. I was surprised, but I successfully called cowboy endpoint and got response.
2. Yes, I used the same architecture. In fact, one of my nodes also works as build server.
3. Ping works, attach also seems to work.

I'm trying to debug it too.

**Comment by bitwalker** [comment]
Well that definitely helps narrow it down, I have to run for a bit, but I'll take a look once I'm at my computer again.

**Comment by rafal-radziszewski** [comment]
Don't you worry, I'm still amazed by the amount of stuff you work on. If I have any more info, I will message here. Thanks for the assistance!

**Comment by rstacruz** [comment]
Also the same problem. Using Ubuntu trusty on AWS.

**Comment by djthread** [comment]
Same issue here, trying to remote_console. Much thanks for all the great work you do, bitwalker!

**Comment by bitwalker** [comment]
I found out what's causing this - the code path has BEAMs which were compiled with earlier Erlang versions, and are thus incompatible with the new version. When it attempts to load BEAMs it needs, it blows up when it encounters the old ones. I was able to reproduce this, and get it to work by blowing away the old release directory and building a fresh release.

I'm going to look in to how to be more precise with adding code paths, so that only those for the current version of the release are added.
